### ISSUE TITLE
hdr file not being read properly

### ISSUE THREAD

**Issue by filefolder** [claudiodsf/nllgrid#4]
Hiya Claudio, nice to see you at work on this lately

I think there is a minor glitch in NLLGrid because I can no longer read the .hdr files properly, reading the file (e.g. `grd = nllgrid.NLLGrid('P.mod')`) outputs the default values instead of the actual ones. 

~ line 203 

```
    def __init__(self,
                 basename=None,
                 nx=1, ny=1, nz=1,
                 x_orig=0., y_orig=0., z_orig=0.,
                 dx=1., dy=1., dz=1.):
        """
        Initialize a NLLGrid object.

        If `basename` is not `None`, `read_hdr_file` and `read_buf_file`
        methods are called.
        """
        if basename is not None:
            self.basename = self.remove_extension(basename)
            self.read_hdr_file()
            self.read_buf_file()
        else:
            self.basename = None
        self.nx = nx
        self.ny = ny
        self.nz = nz
        self.x_orig = x_orig
        self.y_orig = y_orig
        self.z_orig = z_orig
        self.dx = dx
        self.dy = dy
        self.dz = dz
```

Seems like the last 9 lines need to be indented under the `else` clause because otherwise they will always output 1, 1, 1, 0, 0 etc even if basename is not None

**Comment by claudiodsf** [comment]
Hi Robert,
thanks for having pointed that out.

It is now fixed 😉
