### ISSUE TITLE
documentation: plot function

### ISSUE THREAD

**Issue by loicbachelot** [claudiodsf/nllgrid#7]
The plot function the parameter "slice_index" is described as an **int** in the docstring (line 1224 file )
But if we use an **int** there is an error. Seems like the options are None, 'min' or 'max' (see code below):

```
if slice_index is None:
    slice_index = list(map(int, (self.nx/2, self.ny/2, self.nz/2)))
if slice_index == 'max':
    slice_index = self.get_ijk_max()
if slice_index == 'min':
    slice_index = self.get_ijk_min()
```

**Comment by claudiodsf** [comment]
Hi Loic, thanks for reporting! Does the fix in https://github.com/claudiodsf/nllgrid/commit/63c247abc11636b159640655bfaa16e87d3dfbf6 make sense to you?

**Comment by loicbachelot** [comment]
Hi Claudio,
Yes, perfect thanks! Maybe possible to add that the default (None) selects the middle ?
And thanks for the great package

**Comment by claudiodsf** [comment]
Thanks for the feedback. This should be fixed now 😉
